repos:
  - repo: https://github.com/mwouts/jupytext
    rev: v1.13.8
    hooks:
      - id: jupytext
        args: [--sync, --pipe, black, --pipe, "isort - ", scripts]
        additional_dependencies:
          - black==22.3.0
          - isort==5.10.1

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.0
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
