name: bams-manuscript
channels:
  - conda-forge
dependencies:
  - cartopy=0.20.2
  - geopandas=0.10.2
  - matplotlib=3.5.2
  - metpy=1.3.0
  - numpy=1.22.4
  - pandas=1.4.2
  - siphon=0.9
  - xarray=2022.3.0
  - pre-commit
